baseURL = 'https://brunonbn.github.io/investcomrobo.github.io/'
languageCode = 'pt-br'
theme = 'anatole'

[params]
title = 'Investindo com Robôs'
author = 'Bruno Nogueira'
description = 'Automação de trades usando a plataforma MetaTrader 5'
profilePicture = "images/logo-robo.png"
contentratio = 0.7
enableMediumZoom = false
favicon = "favicons/"

[[params.socialIcons]]
icon = "fab fa-youtube"
title = "YouTube"
url = "https://www.youtube.com/BrunoInvest"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/brunonbn/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/brunon_bn"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/brunonbn"