baseURL = 'http://investindocomrobos.com.br/'
languageCode = 'pt-br'
theme = 'anatole'
[params]
title = 'Investindo com Robôs'
author = 'Bruno Nogueira'
description = 'Automação de trades usando a plataforma MetaTrader 5'
profilePicture = "images/icone-robo.png"
